db:
  host: localhost
  port: 5432
  databaseName: ems-auth-db

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.databaseName}
    username: ems-data-user
    password: ems-data-user-pwd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        web.cors: DEBUG

allowed-origins:
  http://localhost:5173,
  http://localhost:8080,
  http://localhost:4200
