server:
  error:
    include-message: always
  port: 8080

spring:
  application:
    name: EMS-API-GATEWAY-SPRING
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: EMS-AUTH-SERVICE-SPRING
          uri: lb://EMS-AUTH-SERVICE-SPRING
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter

        - id: EMS-DATA-SERVICE-SPRING
          uri: lb://EMS-DATA-SERVICE-SPRING
          predicates:
            - Path=/api/v1/data/**
          filters:
            - AuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
