server:
  error:
    include-message: always
  port: 8082

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        web.cors: DEBUG

db:
  host: localhost
  port: 3306
  databaseName: ems-data-db

spring:
  application:
    name: EMS-DATA-SERVICE-SPRING
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.databaseName}
    username: ems-data-user
    password: ems-data-user-pwd
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

allowed-origins:
  http://localhost:5173,
  http://localhost:8080,
  http://localhost:4200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
