server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
spring:
  application:
    name: ems-eureka-registry-spring
