spring:
  application:
    name: ems-api-gateway-spring
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: EMS-AUTH-SERVICE-SPRING
          uri: lb://EMS-AUTH-SERVICE-SPRING
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - AuthFilter

        - id: EMS-DATA-SERVICE-SPRING
          uri: lb://EMS-DATA-SERVICE-SPRING
          predicates:
            - Path=/api/v1/data/**
          filters:
            - AuthFilter

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
#    prefer-ip-address: true
    hostname: localhost
